import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';
import {
  ActionIcon,
  AppShell,
  Box,
  Group,
  Header,
  Navbar,
  rem,
  useMantineColorScheme,
} from '@mantine/core';
import { IconSun, IconMoonStars } from '@tabler/icons-react';

import { MainLinks } from '~/components/shell/Navlinks';
import { User } from '~/components/shell/user';

// import { api } from '~/utils/api';

const Home: NextPage = () => {
  const { colorScheme, toggleColorScheme } = useMantineColorScheme();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <AppShell
          padding='md'
          navbar={
            <Navbar p='xs' width={{ base: 300 }}>
              <Navbar.Section grow mt='md'>
                <MainLinks />
              </Navbar.Section>
              <Navbar.Section>
                <User />
              </Navbar.Section>
            </Navbar>
          }
          header={
            <Header height={60}>
              <Group sx={{ height: '100%' }} px={20} position='apart'>
                <ActionIcon
                  variant='default'
                  onClick={() => toggleColorScheme()}
                  size={30}
                >
                  {colorScheme === 'dark' ? (
                    <IconSun size='1rem' />
                  ) : (
                    <IconMoonStars size='1rem' />
                  )}
                </ActionIcon>
              </Group>
            </Header>
          }
          styles={(theme) => ({
            main: {
              backgroundColor:
                theme.colorScheme === 'dark'
                  ? theme.colors.dark[8]
                  : theme.colors.gray[0],
            },
          })}
        >
          {/* Your application here */}
        </AppShell>
      </main>
    </>
  );
};

export default Home;
